# This is an example configuration file
# To learn more, see the full config.yaml reference: https://docs.continue.dev/reference

name: Example Config
version: 1.0.0
schema: v1

# Define which models can be used
# https://docs.continue.dev/customization/models
models:
  - name: glm-5.1
    provider: openai
    model: glm-5.1
    apiKey: sk-r0YNASfEFmtY5Un88Cktaw
    apiBase: https://ai.sumopod.com/v1

context:
  - provider: currentFile
  - provider: codebase
  - provider: diff
  - provider: terminal
  - provider: file
